# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38f60fad51ed5c14acbddf0b8215b0d438231b39ff9b4093796d847cbe10946828e12a1cc834d5ca2599d017b2fdc092391f6419e68abafb1934e612cd9d2273

test:
  secret_key_base: 9cdd819f988e5496ce777e11d766cdb75a1b37433dbb7010793142c896a1f5b97b68ea8d82667b67cb26064d2c7763e4ee44d2dd93b23ee08da9e2a374bd1fcc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
